### ISSUE TITLE
Would this be better than IPC communication via child workers?

### ISSUE THREAD

**Issue by McFarts** [vpj/node_shm#1]
I want to utilize more cores on my nodejs app, but if I fork a child process.. I have to send all my objects and game data to it for it to be useful....  Was wondering if I use this, I won't have that problem since the memory is going to be shared right?

**Comment by vpj** [comment]
Yes

**Comment by McFarts** [comment]
@vpj I thought you and this project was dead! Ha, thank you for this, much much better as compared to use redis / memcache because for my gameserver I have some specific monster ai looping and players data is stored in the buffer and it would just be insane to send it all through the ipc. I cannot wait to get this addon working correctly, I'm very excited. Closed

**Comment by vpj** [comment]
However, I created this node module as an experiment. And I have not done any updates on this. So you might come across a lot of bugs running it. I created this git repo while writing this blog post http://vpj.github.io/node_shm.html.

**Comment by McFarts** [comment]
Yeah, that's where I first found about it, by googling and ended up here:

http://blog.varunajayasiri.com/shared-memory-with-nodejs

I want to get it working and then test it out with my loops and see how it does, it will work under debian I'm sure, right?

**Comment by vpj** [comment]
Yes it should work on debian. I tested this on ubuntu, and on mac os, with a help of a friend.

**Comment by vpj** [comment]
I just came across this fork https://github.com/lpetre/node-shm-buffer

**Comment by McFarts** [comment]
@vpj  Sweet. Do you think I should use that instead?

I do see:
```
#include <sys/ipc.h>
```

So, a linux only one right? If so, that's fine just wish I could get my hands on a Windows one too, great find nonetheless! Ty for the info

**Comment by vpj** [comment]
yes that's only linux
