### ISSUE TITLE
C++ exc eption handler used, but unwind semantics are not enabled. Specify /EHsc [C:\WT-NMP\apps\build\shm_addon.vcxproj]

### ISSUE THREAD

**Issue by McFarts** [vpj/node_shm#2]
```

C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exc
eption handler used, but unwind semantics are not enabled. Specify /EHsc [C:\WT-NMP\apps\build\shm_addon.vcxproj]

```

Hmm. any idea?

Trying to install on windows 7 64 bit, got visual studio and python and everything Hmm.

Full Error:
![](https://i.gyazo.com/8ae24f4e0a6f6be3b88e4fd09b6b4477.png)

**Comment by vpj** [comment]
Sorry, this module uses shared memory functions on linux http://linux.die.net/man/2/shmget
And the module only compiles on linux. There is a way to share memory on windows as well https://msdn.microsoft.com/en-us/library/windows/desktop/aa366878(v=vs.85).aspx. This is something I would like to try out in the future.

**Comment by McFarts** [comment]
Aww shucks!! Yeah, I just noticed 

#include <sys/ipc.h>
#include <sys/shm.h>

Is there any way to download these and have them be working on windows just so I can get this thing compiled and working?

If not, should I install/run debian on a virtual machine or whatnot and just test it that way? This sucks :( haha.

**Comment by vpj** [comment]
I don't think there's a way to download and get it working on windows, as this is a OS level functionality.

**Comment by vpj** [comment]
Also make sure you set the shared memory limits when you run it in production 
ref: http://seriousbirder.com/blogs/linux-understanding-shmmax-and-shmall-settings/

**Comment by McFarts** [comment]
Awww I see.

No problems. I'll just install debian on vmware I guess or some type of virtual machine and develop / test it through there.

Thanks for your help, I will subscribe to your website and if u ever make a windows one, I'll be there!
